#!/bin/bash
if [[ "$1" == "list" ]]; then
  echo "Listing..."
  # shellcheck disable=SC2154
  for p in ${STUB_UPGRADABLE:-}; do
    echo "$p/stable 1.2-3 amd64 [upgradable from: 1.2-2]"
  done
fi
exit 0
